//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIU.CorporateWebsite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string IdName { get; set; }
    }
}
