//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIU.CorporateWebsite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseUser
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string Code { get; set; }
        public string RealName { get; set; }
        public string QuickQuery { get; set; }
        public Nullable<int> SecurityLevel { get; set; }
        public string UserFrom { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> SubCompanyID { get; set; }
    }
}
