//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIU.CorporateWebsite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public string NewsTitle { get; set; }
        public Nullable<int> Cid { get; set; }
        public string Source { get; set; }
        public string Contents { get; set; }
        public string Author { get; set; }
        public string SubTitle { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<bool> IsRecommend { get; set; }
    }
}
