//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIU.CorporateWebsite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCategory
    {
        public int ID { get; set; }
        public string CName { get; set; }
        public Nullable<int> Pid { get; set; }
        public string Description { get; set; }
        public string CImg { get; set; }
    }
}
