//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIU.CorporateWebsite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string PName { get; set; }
        public string BriefIntroduction { get; set; }
        public Nullable<int> PCid { get; set; }
        public string PImg { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string PContent { get; set; }
        public Nullable<bool> IsRecommend { get; set; }
    }
}
